### PR TITLE
Fixing test failure on Windows

### LINKED ISSUE #91: Test failure on Windows
Test failure on Windows,

```
× config - Should strip .template from fileName (0.015s)
AssertionError: expected '/foo/bar\\.gitignore' to equal '/foo/bar/.gitignore'
  at Function.assert.equal  <node_modules\intern\browser_modules\chai\chai.js:2277:10>
  at Test.Should strip .template from fileName [as test]  <tests\unit\config.ts:27:9>
  at <node_modules\intern\lib\Test.js:191:24>
  at <node_modules\intern\browser_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <node_modules\intern\browser_modules\dojo\Promise.ts:11:11>
  at <node_modules\intern\browser_modules\dojo\Promise.ts:317:4>
  at run  <node_modules\intern\browser_modules\dojo\Promise.ts:237:7>
  at <node_modules\intern\browser_modules\dojo\nextTick.ts:44:3>
  at _combinedTickCallback  <internal\process\next_tick.js:73:7>
  at process._tickCallback  <internal\process\next_tick.js:104:9>
```

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code matches the [style guide](https://github.com/dojo/meta/blob/master/STYLE.md)
* [x] Unit or Functional tests are included in the PR

**Description:**

Fixing test failure on Windows.  Path is properly converted to `\\` separator on Windows now.

Resolves #91

### CODE REVIEW

File: src/config.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ const fileNames = [
 export function stripTemplateFromFileName(filePath: string) {
 	const path = parse(filePath);
 	path.base = path.base.replace('.template', '');
-	return format(path);
+	return normalize(format(path));
```
Comment (rorticus) [inline src/config.ts:41]: Without normalizing the path we get something like `/foo/bar/\\.gitignore` which is kind of weird, but I think technically works.

**Review by maier49 — APPROVED** [review]

**Review by agubler — APPROVED** [review]

File: src/config.ts [hunk 2]
```diff
@@ -1,4 +1,4 @@
-import { join, parse, format } from 'path';
+import { join, parse, format, normalize } from 'path';
```
Comment (kitsonk) [inline src/config.ts]: As long as we are touching this, it would be create if we alphabetised this.

Comment (rorticus) [reply src/config.ts]: Done!

**Review by kitsonk — APPROVED** [review]
